### ISSUE TITLE
l10n: Translations need to be updated

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint21.1-beta#1]
LP translations can't be downloaded right now.

https://bugs.launchpad.net/launchpad/+bug/1998037
https://bugs.launchpad.net/launchpad/+bug/1998616

This needs to be fixed or a workaround needs to be found before STABLE.

Progress
=======

Edit: There's no sign of Launchpad getting fixed, so we're going to have to get these manually somehow. Here's a list of templates remaining:

**cinnamon-translations**

- [x] cinnamon
- [x] cinnamon-control-center
- [x] cinnamon-screensaver
- [x] cinnamon-session
- [x] nemo

**XApps**

- [x] bulky
- [x] folder-color-switcher
- [x] hypnotix
- [x] lightdm-settings
- [x] nvidia-prime-applet
- [x] pix
- [x] slick-greeter
- [x] sticky
- [x] thingy
- [x] warpinator
- [x] webapp-manager
- [x] xapp
- [x] xfce4-xapp-status-plugin

**mint-transltions**

- [x] mintbackup
- [x] mint-common
- [x] mintdesktop
- [x] mintinstall
- [x] mintlocale
- [x] mintmenu
- [x] mintnanny
- [x] mintsources
- [x] mintstick
- [x] mintupload
- [x] mintwelcome

**Mint tools**

- [x] mintdrivers
- [x] mintreport
- [x] mintupdate
- [x] mintupgrade

**Other**

- [x] slideshow-mint
- [x] mintubiquity

**No new msgids**

- [x] cinnamon-settings-daemon
- [x] nemo-extensions
- [x] timeshift
- [x] xed
- [x] xreader
- [x] xviewer

**Comment by clefebvre** [comment]
Translations for the following projects weren't updated in BETA:

cinnamon
cinnamon-control-center
cinnamon-settings-daemon
mintupdate
nemo
nemo-extensions
pix
timeshift
xed
xreader
xviewer

**Comment by hugok79** [comment]
Maybe Linux Mint translation should start using other translation platforms like **Transifex** or **Weblate**...

**Comment by clefebvre** [comment]
The community of translators on LP is doing a fantastic job.

**Comment by hugok79** [comment]
Yes it is. I translate the Portuguese language https://translations.launchpad.net/linuxmint/latest/+lang/pt
But I also translate **mate** and **xfce** at Transifex. Which is why I mentioned this alternative to Launchpad.

**Comment by jakoblm** [comment]
Please also correct the spelling mistake in the German translation, which has crept in since at least Mint 21. In the display settings "Bildschirmscalierung" should be written "Bildschirmskalierung" with "k".  See second image in the following issue: https://github.com/linuxmint/mint21.1-beta/issues/33. Thanks.

**Comment by clefebvre** [comment]
Timeshift has no new msgids since Mint 21 so this one is OK.

**Comment by clefebvre** [comment]
Same for xed, xviewer, xreader.

**Comment by hugok79** [comment]
> Please also correct the spelling mistake in the German translation, which has crept in since at least Mint 21. In the display settings "Bildschirmscalierung" should be written "Bildschirmskalierung" with "k". See second image in the following issue: #33. Thanks.

@jakoblm  https://github.com/linuxmint/cinnamon-translations/pull/43#event-8029011393

**Comment by clefebvre** [comment]
OK, we've got translations for cinnamon-session and cinnamon-screensaver... 

The only remaining templates we can't download translations for yet are:

- cinnamon
- cinnamon-control-center
- nemo

I'm going to try and force a regeneration of their PO files in Launchpad by modifying the POT and their internal path. We can then hopefully get them via Bzr.

I tried downloading them even with just a few languages (down to just 3) and even that fails :(

**Comment by hugok79** [comment]
I can download those 3 **.po** or **.mo** files from Launchpad... Can I help in any way?

**Comment by clefebvre** [comment]
Where do you get them from @hugok79 ? Can you give me a link?

**Comment by hugok79** [comment]
From Launchpad.
**The .po files:**
https://launchpadlibrarian.net/639798768/cinnamon_cinnamon-pt.po
https://launchpadlibrarian.net/639798769/cinnamon-control-center_cinnamon-control-center-pt.po
https://launchpadlibrarian.net/639798770/nemo_nemo-pt.po

**The .mo files:**
https://launchpadlibrarian.net/639798861/pt_LC_MESSAGES_cinnamon.mo
https://launchpadlibrarian.net/639798865/pt_LC_MESSAGES_cinnamon-control-center.mo
https://launchpadlibrarian.net/639798875/pt_LC_MESSAGES_nemo.mo

Or if you want I can forward you the emails I received from Launchpad to your email, if you want

**Comment by clefebvre** [comment]
Ah ok, I understand. No that works for me too... I can download individual languages one by one. This would be super tedious though. I'm going to try the bzr method.

**Comment by clefebvre** [comment]
OK, it looks like it worked, I think we're going to be OK.

**Comment by jakoblm** [comment]
Looks good. Thanks. Only one German translation was overlooked: In Nemo, "Path Bar" and "Location Entry" should be translated into German. See also picture 4 in the following issue: https://github.com/linuxmint/mint21.1-beta/issues/33.
