### ISSUE TITLE
Port to Aqua? Why?

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.1-beta#10]
ref my comment on #7

**Comment by carlosmintfan** [comment]
And the folder icons look differently and the mouse too (didn't download and run the iso actually, just from what I see in screenshots and screenrecords here...). Well, but is the theme like it is in Vanessa also available there?

**Comment by carlosmintfan** [comment]
And the old pointers?

**Comment by okaestne** [comment]
> Well, but is the theme like it is in Vanessa also available there?

Yes, renamed to "Mint-Y-Legacy-\<color\>".

> And the old pointers?

Just download the iso and find out?

**Comment by Acheron17** [comment]
The old pointers are still there under System Settings -> Themes -> Mouse Pointer.  On your boot up and log in you can also set the Mouse pointer.  System Settings -> Login Window -> Themes -> Mouse pointer.

**Comment by carlosmintfan** [comment]
@okaestne Thanks, but the legacy themes should be the ones like the were, well, in 20.1 or something like that, or in 19.3, that ones, with the corners not rounded, at least not like in 20.3 and 21, and the smaller close button... Are you sure they were renamed like that?

**Comment by carlosmintfan** [comment]
But the corners are something like rounded or so even in the legacy ones, in the package mint-themes-legacy, well, whatever. But the standard theme is Aqua, isn't it? Is the available green darker? And other folder icons... Well, whatever, but probably I'll try the ISO soon. I have the vera repo on my Vanessa, but not applied all updates, or just applied some updates, well, whatever...

**Comment by carlosmintfan** [comment]
In #4 you can see "green" in the old and in the new mintwelcome. But these seem to be different.

**Comment by clefebvre** [comment]
The default color variation in 21.1 is indeed Aqua.

This is explained in https://www.linuxmint.com/rel_vera_cinnamon_whatsnew.php.

The legacy options are installed by default and correspond to the look and feel of Linux Mint 20.2.
