### ISSUE TITLE
upstream: mesa 20.0.5 causes artifacts for at least Radeon 5600XT gpus

### ISSUE THREAD

**Issue by tethragon** [linuxmint/mint21.1-beta#13]
**Mesa 20.0.5 drivers** cause strange artifacts (AMD Radeon 5600XT) for some apps like gimp or libreoffice, but NOT in others like firefox, chrome. Also these artifacts appear **on the desktop icons as well**. Please see attached screenshots

![205681912-b71f5c28-018b-4792-97a5-af8d59bb0987](https://user-images.githubusercontent.com/39238674/205730273-904a2d0f-4de6-4d1b-b891-503ad0bc6bdb.jpg)

![205681943-121e3ee9-8478-4c7d-82f0-93df9c57b4cb](https://user-images.githubusercontent.com/39238674/205730292-9f18d8e3-184b-46fa-8120-d6a2afb66136.jpg)

Issue is resolved after upgrading mesa drivers (using oibaf ppa). I use now mesa 23.0.0 and there are no artifacts. This ppa is a little "dangerous" to break the system, so **maybe mint team should consider to use an updated mesa driver for the default installation.**

see also: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4811

**Comment by clefebvre** [comment]
That's definitely upstream-wontfix for us. That said we can add this to the release notes. Do you have a bug report on Ubuntu 22.04 for this?

**Comment by tethragon** [comment]
> That's definitely upstream-wontfix for us. That said we can add this to the release notes. Do you have a bug report on Ubuntu 22.04 for this?

I am sorry, I don't have an Ubuntu 22.04 bug report for this.

**Comment by clefebvre** [comment]
OK, it's known upstream:

https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1979053

Fixed in mesa 22.2. Will land in Mint 21.x when backported to Ubuntu 22.04.
