### ISSUE TITLE
webapp-manager: edit the url of the webapp removes it from the menu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.1-beta#14]
steps to reproduce:

1- create a webapp and write its url from the 'www'
2- confirm the visualization in the menu
3- edit the url to an https connection

edit: the problem also happens when entering a url from the https protocol and changing it to http

https://user-images.githubusercontent.com/68134588/205741734-130430af-7f52-451d-885d-e8c3c4704432.mp4

Obs: There is no option to change the browser to use when editing a webapp. To change browser you have to add another webapp from scratch.

**Comment by Kroksandgraven** [comment]
When choosing an other icon then the default icon during creation of a web application with Brave Browser no entry to start the application will be created in the cinnamon menu as if you had chosen Firefox Browser.  The application with "edited Icon" is present and executable in the Webapp window just missing an entry in the Cinnamon menu.

**Comment by clefebvre** [comment]
Fixed in webapp-manager 1.2.8
