### ISSUE TITLE
artwork: inconsistent theming in Driver Manager

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mint21.1-beta#17]
In Vera Cinnamon what's-new I saw this picture (didn't test it in ISO):
https://www.linuxmint.com/pictures/screenshots/vera/mintdrivers-mount.png
Selected theme seems to be Aqua, but the button "Mount installation media" is green / not themed.

**Comment by SebastJava** [comment]
There is no mistake there. That button is `#6db442`. That's `$suggested_color: #6db442;` as set in https://github.com/linuxmint/mint-themes/blob/master/src/Mint-Y/gtk-3.0/sass/_colors.scss

EDIT: In other words, this color is independent from the theme's color, it is green to encourage you to click on it... Same thing for the "=" button on the calculator, for example...

**Comment by clefebvre** [comment]
Thanks @SebastJava, that's exactly that. Suggested actions are green, destructive actions are red, in all theme color variations.
