### ISSUE TITLE
New Features in Linux Mint 21.1 Cinnamon has a small labeling error

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint21.1-beta#18]
See: https://www.linuxmint.com/rel_vera_cinnamon_whatsnew.php
Scroll down to: Other Improvements
It was noticed the label for the screen shot of the Software Sources it was labeled as "Duplicating a note in Sticky Notes"
Screenshot attached.

![image](https://user-images.githubusercontent.com/45599505/205943285-15453f1e-e88c-4a70-9e6c-0645817361ee.png)

**Comment by clefebvre** [comment]
Thanks @Harry-W-Haines-III, fixed.
