### ISSUE TITLE
mintdrivers: Can't go back to main screen from the error page

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint21.1-beta#19]
System is fully updated.
According to: https://www.linuxmint.com/rel_vera_cinnamon_whatsnew.php
Section: "Driver Manager"
"User Interface
The manager now runs in user mode so you no longer need a password to launch it."

But it does require a password to make any changes.  When the password is not given and you press "Cancel" it errors out with a message not seen before (see screenshot number 2).   Then the Driver Manager hangs after pressing "OK" on the error message.  See screenshot number 3.  Pressing "Cancel" has no effect and you have to close it out with the upper right hand "X'.

![Screenshot from 2022-12-06 09-56-54](https://user-images.githubusercontent.com/45599505/205948686-aa8643cf-b269-46b3-81d3-e29b60da6eb6.png)

![Screenshot from 2022-12-06 09-57-15](https://user-images.githubusercontent.com/45599505/205948719-49dd6dba-819f-4d86-bb0e-d1d33c84fddd.png)

![Screenshot from 2022-12-06 10-00-48](https://user-images.githubusercontent.com/45599505/205948747-dae96e68-64e7-442f-a941-0761cbf02914.png)

Expected results would be to return to the Driver Manager screen and click "Cancel" to close the Driver Manager.

Note: For the purpose of this test I was attempting to re-install the Open Source video drivers.

**Comment by clefebvre** [comment]
It definitely needs a password when making changes, there's no way around that.

Not being able to go back is indeed a bug though.

**Comment by clefebvre** [comment]
Fixed in mintdrivers 1.6.7
