### ISSUE TITLE
slick-greeter: Round battery percentage

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint21.1-beta#2]
During testing the battery percentage appeared as 70.00000011010110001% :)

**Comment by anaximeno** [comment]
This also happens in the Vanessa edition, so the fix could also be backported if it would be necessary.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/slick-greeter/commit/2f43e0392f03fadbc76448abf733e61ab44daad9
