### ISSUE TITLE
mintupdate: Updating a flatpak shows inconsistent download size

### ISSUE THREAD

**Issue by mantuoliveira** [linuxmint/mint21.1-beta#21]
When using update manager to update mesa, the download size is inconsistent.

 
![Screenshot from 2022-12-06 19-23-56](https://user-images.githubusercontent.com/66520569/206039649-db773afd-8ff3-4450-9218-fbb31cdde19c.png)

**Comment by Tibladar** [comment]
The download size comes from flatpak itself, mintupdate just displays it.
It's the same behaviour when updating through `flatpak update`

**Comment by clefebvre** [comment]
Confirmed. The entire string comes from Flatpak itself.
