### ISSUE TITLE
mintinstall: uninstalling flatpak does not work from the cinnamon menu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.1-beta#23]
1- install a flatpak application
2- confirm launch from the menu
3- uninstall from the cinnamon menu

...

 [tested on live usb]

https://user-images.githubusercontent.com/68134588/206075516-e3949144-842a-429b-ad1c-6352eed860d8.mp4

[logs.zip](https://github.com/linuxmint/mint21.1-beta/files/10172354/logs.zip)

**Comment by clefebvre** [comment]
Thanks @haggen88 can you try with mint-common 2.2.3?

**Comment by haggen88** [comment]
2.2.3 is the version that is running... 
![223](https://user-images.githubusercontent.com/68134588/206223018-4f86b4af-1a6f-4971-aa99-0299820839ad.png)

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/206229055-3be7e8d2-01da-488a-9851-79a746063b64.png)

**Comment by mtwebster** [comment]
Fixed by:
https://github.com/linuxmint/mintinstall/commit/e232ca6537df25a39168c0558de1bfc580a148fd
