### ISSUE TITLE
cursor: wrong cursor used in qt apps

### ISSUE THREAD

**Issue by scoson** [linuxmint/mint21.1-beta#27]
Sorry in advance if this is incomplete/formatted wrong in advance, I really don't belong on github :)

I use the DMZ white cursor, so I switched back to it pretty much right away, but noticing that QT apps are using the Bibata black cursor that is default with install when hovering over them. I did an upgrade, not clean install, if it matters. If not hovering over app window, or even on titlebar, DMZ is shown again. I noticed this with Hydrogen, MusE, and so I thought I'd check QT5 settings, and sure enough, there too.

**Comment by clefebvre** [comment]
Hi @scoson,

Try to set the cursor theme globally for X11 using the alternative system:

`sudo update-alternatives --config x-cursor-theme`

**Comment by scoson** [comment]
> Hi @scoson,
> 
> Try to set the cursor theme globally for X11 using the alternative system:
> 
> `sudo update-alternatives --config x-cursor-theme`

Yes, that worked, thanks..

**Comment by NintendoManiac64** [comment]
This happens in even the live ISO however - you can easily verify it by just opening Celluloid.

**Comment by NintendoManiac64** [comment]
This also happens even in the live ISO on Cinnamon, Mate, and Xfce.

Furthermore, with Celluloid, the player area as well as the borders still use the Bibata cursor even though the toolbars, player controls, and the desktop in general were set to DMZ-white.

[cinnamon.webm](https://user-images.githubusercontent.com/11896003/206563983-eb280e24-e8e1-4004-874c-1760b0d88a26.webm)

[mate.webm](https://user-images.githubusercontent.com/11896003/206570394-fd78eb58-beb2-4a8c-8105-5dda1f84ba5f.webm)

[xfce.webm](https://user-images.githubusercontent.com/11896003/206570409-bc75929f-6f2b-4eb7-8e52-537f2fab05c6.webm)

**Comment by leonardo-47** [comment]
Mouse Cursors available by default like Bibata Ice(Original and Modern), Bibata Original Classic, Xcursor pro, Google Dot and Yaru  are not listed as choices when attempting to set default cursor theme via  `sudo update-alternatives --config x-cursor-theme`. 

![bibata_ice_missing](https://user-images.githubusercontent.com/120299908/206891682-fd2440fa-b7f9-4994-bf69-8337133cfef3.png)

**Comment by wolkzel** [comment]
Steam (Flatpak) uses different cursor theme even though Bibata-Modern-Classic cursor theme is system default.

https://user-images.githubusercontent.com/46371662/206900123-eb658395-ed52-4857-81ff-0fe189455777.mp4

**Comment by anaximeno** [comment]
@wolkzel can you confirm if the solution in the link below solves the problem?

https://www.reddit.com/r/flatpak/comments/rxnyh7/comment/hwvsut5/?utm_source=share&utm_medium=web2x&context=3

**Comment by wolkzel** [comment]
@anaximeno Sadly that solution didn't work for Steam. I gave permissions before launching, after that Steam didn't open even though I tried to open it many times. I had to reset the permissions of Steam to open it again.

**Comment by clefebvre** [comment]
update-alternative options added for alternative themes in mint-cursor-themes 1.0.1

**Comment by clefebvre** [comment]
For Flatpak, I'm not sure what's going on. I could reproduce the issue initially before using Flatseal.. (also Steam indeed breaks when given access to home). After giving apps home and/or system files access though, the pointer works for me, even after I disable these again.

I added info in the release notes about update-alternatives, Qt and Flatpak apps.

**Comment by waynemaranga** [comment]
> Hi @scoson,
> 
> Try to set the cursor theme globally for X11 using the alternative system:
> 
> `sudo update-alternatives --config x-cursor-theme`

This worked for me. Results were clear after restarting the computer
