### ISSUE TITLE
Unable to open lightdm-settings after upgrading to version 1.6.0

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint21.1-beta#29]
**Issue**
My apologies if this doesn't go here, but I'm doing a particular testing after upgrading lightdm-settings package on Arch and after upgrading from 1.5.9 to 1.6.0, I have an error that says "Settings schema 'x.dm.slick-greeter' does not contain a key named 'cursor-theme-name'", maybe is there a particular key that is missing or a process that I should follow in order to add this particular key?

Maybe this is something that you can take into consideration when upgrading from Mint 21 to Mint 21.1, since as I understand the version on that program on Mint is either 1.5.9 or 1.5.10 and to prevent the users to have the program with issues

**Steps to reproduce**
1) Upgrade lightdm-settings from 1.5.9 to 1.6.0, this includes the newer as per your Github "Add a setting to configure the cursor-theme-size"
2) Start lightdm settings via menu or via terminal

**Actual behaviour**
Error "GLib-GIO-ERROR **: 09:05:44.354: Settings schema 'x.dm.slick-greeter' does not contain a key named 'cursor-theme-name'" appears when running on terminal. Using the menu and GUI doesn't open at all

**Expected behaviour**
lightdm-settings should open with no issues

**Other information**
I follow [this process](https://askubuntu.com/questions/150991/settings-schema-gnome-org-desktop-a11y-magnifier-does-not-contain-a-key-named) to set the key manually with no success, [this one](https://techienotes.blog/2021/10/11/how-to-get-rid-of-glib-gio-error-settings-schema-does-not-contain-a-key-on-gnome-40/) to try if my particular settings have an issue, also while checking dconf-editor on the given path, I actually do not have any "cursor-theme-name" key available there

**Comment by ghost** [comment]
I have managed to "fix it" by manually adding the required keys "cursor-theme-name" and "cursor-theme-size" (another error I encounter while doing additional tests) and then recompile the schemas, however, I'm not sure if this is the way I should handle, although adding keys manually I am probably messing with the original package

`    <key name="cursor-theme-name" type="s">
      <default>'Adwaita'</default>
      <summary>Mouse pointer theme to use</summary>
    </key>
    <key name="cursor-theme-size" type="d">
      <default>96</default>
      <summary>Resolution and size of the cursor theme</summary>`

Since I don't have a beta of Linux Mint installed on the PC i'm working with, I'm unable to compare if the keys and settings are the exact same thing so I can try to add those manually, I just hope that manually doing this process shouldn't be the way since many users might not be tech-savy to perform this

**Comment by leigh123linux** [comment]
slick-greeter-1.6.0 provides the missing key.

**Comment by ghost** [comment]
Thanks for the information @leigh123linux , I can confirm that this version works and provides the missing keys that I reported, thanks once again and my apologies for taking your time
