### ISSUE TITLE
artwork: Tooltip border color

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint21.1-beta#3]
The tooltip border color is light grey, it's especially visible in Cinnamon. It would probably look better:

- plain (i.e. no border)
- or with a darker tint of yellow

**Comment by SebastJava** [comment]
Further more enhancement suggestion: a very different background-color for dark vs light variants...

```
// in src/Mint-Y/gtk-3.0/sass/_colors.scss and src/Mint-Y/gtk-4.0/sass/_colors.scss :

$tooltip_bg_color: if($variant == 'light', #fff7cc, #5a3636);
```
These colors are mine. I really don't like a heavily darkened yellow, so i preferred a subtle yellowish white for light themes, and a reddish dark gray for dark themes. The initial suggestion for different tooltips on dark themes was made a long time ago by @claudiux on my own Mint-Yz fork repository.

**Comment by ghost** [comment]
The yellow background in the tooltips #fbeaa0 is different from the yellow folder colour in the new Mint-Y themes. This is a little jarring, especially when using Nemo.

My preference would be for a white background for light themes and a black background for dark themes. This would match Qt apps when using the default Mint gtk2 qt5ct settings (which do not use a yellow background).

If that is not chosen, matching the yellow tooltip background to the yellow folder background would give a more consistent appearance than currently.

As to the border colour, I would prefer plain (i.e. no border).

**Comment by clefebvre** [comment]
Removing the border isn't enough, we need to make sure shadows are consistent also.

Adwaita is using a semi-transparent rounded black tooltip. This could work well. We need to take our time and experiment with all this.

Moved to 21.2's roadmap.

**Comment by ghost** [comment]
> Adwaita is using a semi-transparent rounded black tooltip. This could work well. We need to take our time and experiment with all this.
> 
> Moved to 21.2's roadmap.

That could indeed work well. I can edit the tooltips myself in the meantime. Thank you.
