### ISSUE TITLE
Differences in "System Info" in Linux Mint and others

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint21.1-beta#30]
**Issue**
As per [Cinnamon "whats new"](https://www.linuxmint.com/rel_vera_cinnamon_whatsnew.php): "The system info screen shows the operating system logo". However, when you want to check on other distros outside of Linux Mint, it doesn't show neither the icon nor the options "Upload system information" and "Copy to clipboard". 

I'm not sure if these 3 options use something particular from Linux Mint/Debian/Ubuntu/deb-based distros (which in this case I suppose there is a particular package I have forgotten about), or if this is distro-agnostic, however, just in case and for my (and probably everyone) information I report and if it is possible to fix it (if it is a bug) or something that will remain like that (in case is something particular)

**Steps to reproduce**
1) Go to Cinnamon menu - System Settings
2) Inside the settings, look for the option "System Info"
3) It shows the information of the operative system

**Actual behaviour**
It doesn't show neither the distribution icon nor the options "Upload system information" and "Copy to clipboard"

**Expected behaviour**

It shows the icon of the distribution as well as the options "Upload system information" and "Copy to clipboard"

**Other information**

System Info on Linux Mint 21

![MintInfo](https://user-images.githubusercontent.com/1509924/206516434-d0d837c7-4653-4ca6-a42f-494e80d1cdd5.png)

System Info on Arch Linux (fully updated)

![ArchInfo](https://user-images.githubusercontent.com/1509924/206516462-f583af8b-7c89-4fd1-a4e4-9db79993e69a.png)

**Comment by mtwebster** [comment]
The two buttons are dependent on whether or not you have the 'upload-system-info' program in your path (for Mint it's provided by xapp-common package), and 'inxi' installed, respectively.

The logo is something that needs to be handled by your Cinnamon maintainer for arch - there's a 'system-icon' they can set with an icon name or path to an image. By default it's empty, so there's no image. You can set it yourself if you like:

```
gsettings set org.cinnamon system-icon "<path or icon name>"

**Comment by ghost** [comment]
I see, I will continue to check and to perform some tests, but at least after what you told me I have the option to look for something and also I manage to install a Mint VM, I appreciate the help

EDIT:
Also, if I may ask, do you know that are the dimensions of the icon that I can use in order to put that option in other distros? I understand that this is out of a bug-fixing scope but I would like to know in case I may try to set it up manually
