### ISSUE TITLE
Nemo does not remember the setting "Toggle Location Entry"

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint21.1-beta#32]
LM 21.1 Beta Cinnamon Live-System:

In Nemo "Toggle Location Entry" does not remember my setting. Although I have switched to the editable address bar, the setting resets as soon as I open a new window or folder.

**Comment by mtwebster** [comment]
This was touched on in https://www.linuxmint.com/rel_vera_cinnamon_whatsnew.php.

Location entry is temporary, by default, now. You can click on the pathbar and temporarily get the location bar (or hit / or ctrl-L), but once you change location it resets back to the pathbar.

You can go to he View->Toolbar menu to permanently select the location entry.

**Comment by jakoblm** [comment]
Thank you for the explanation. I had actually overlooked that.
