### ISSUE TITLE
German translations are missing

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint21.1-beta#33]
LM 21.1 Beta Cinnamon:

Some German translations are missing. 

1) In the login settings "Mouse Pointer" should be translated as "Mauszeiger" and "Mouse Pointer Size" as "Mauszeigergröße".
![1](https://user-images.githubusercontent.com/51761218/206538317-ba92cc66-9b3d-499b-a93d-53874b28e6e1.jpg)

2) In the display settings "Bildschirmscalierung" should be written "Bildschirmskalierung".
![2](https://user-images.githubusercontent.com/51761218/206538393-5ead9201-b7c8-494f-a454-ea4fd166dc6d.jpg)

3) In the window settings "Location of newly opened windows" should be translated as "Position der neu geöffneten Fenster".
![3](https://user-images.githubusercontent.com/51761218/206538464-664c2572-efb8-481a-b2ac-7c928966d65f.jpg)

4) In Nemo, "Path Bar" and "Location Entry" should be translated into German.
![4](https://user-images.githubusercontent.com/51761218/206687057-89a27f2e-9702-4b92-8576-8f74a9d0c9a5.jpg)

5) In Update Manager, "Update Manager is not responding." should be translated as "Aktualisierungsverwaltung antwortet nicht." The same applies to "Checking for flatpak updates", in German "Prüfe auf Flatpak Aktualisierungen".
![5](https://user-images.githubusercontent.com/51761218/206687200-0d3812b1-f621-4128-b9e6-3cd12c9b2540.jpg)

**Comment by mtwebster** [comment]
This is caused by #1 I believe

**Comment by carlosmintfan** [comment]
@jakoblm The "is not responding" window isn't part of Update Manager but of Cinnamon or so :)

**Comment by hugok79** [comment]
German translations of Linux Mint are made in https://translations.launchpad.net/linuxmint/latest/+lang/de
