### ISSUE TITLE
nemo: File gtk menu scrollbar issue on file selection

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#34]
(curiously, this does not occur on Mate nor Xfce if you install Nemo on either...)

[cinnamon.webm](https://user-images.githubusercontent.com/11896003/206588790-6695a838-d566-40a1-a000-7b83c32e1914.webm)

**Comment by clefebvre** [comment]
That's a classic case of GTK Menu bug. The reason it usually happens is because we rebuilt/modify the menu on file selection.

@mtwebster what do you think?

**Comment by mtwebster** [comment]
It doesn't happen if only muffin is running either..
