### ISSUE TITLE
[Cinnamon & Xfce] Installing 'Caja' or 'Mate-system-monitor' does not add it to the applications menu (Mint's equivalent of the Windows start menu)

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#35]
(curiously, this does not occur on Mate even if you uninstall then re-install it...)

While the videos only depict the installation of 'Mate-system-monitor', the exact same issue also occurs if you install 'Caja' on Cinnamon and/or Xfce.

[cinnamon.webm](https://user-images.githubusercontent.com/11896003/206598650-5f64f619-0af9-4a68-9968-646a2b5a733f.webm)

[xfce.webm](https://user-images.githubusercontent.com/11896003/206598832-430151bd-a48f-4bd2-b59e-454c25f888bd.webm)

**Comment by mtwebster** [comment]
This is deliberate - in both of their desktop files (`/usr/share/applications`) is an `OnlyShowIn` entry that specifies which desktop environments to be 'visible' in:
![image](https://user-images.githubusercontent.com/262776/206621829-74b4df06-743c-4e33-b8e0-d857df8ac217.png)

You'll have to create a custom desktop file or launcher, or you can stick a copy of their original desktop files in ~/.local/share/applications and take out that line.
