### ISSUE TITLE
Nemo & Caja - when typing a long file name for a file on the bottom of the list, the text goes out of view and below the bottom of the scrollable area

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#37]
This occurs regardless of desktop environment (e.g. Cinnamon + Caja, Xfce + Nemo, etc), though obviously does not occur with Thunar since its file-rename method uses a popup text window instead.

[cinnamon.webm](https://user-images.githubusercontent.com/11896003/206617592-46f2e1d3-f56a-41dc-af53-359edc1385ad.webm)

[mate.webm](https://user-images.githubusercontent.com/11896003/206617596-dcb9e331-3bae-4d18-81b4-243d9dd9189c.webm)

**Comment by clefebvre** [comment]
Not a blocker but needs to be looked at post-release.

**Comment by clefebvre** [comment]
Tag added to roadmap.
