### ISSUE TITLE
Caja - newly-created files or folders don't automatically go into rename-mode if they're the first file of a row that's partially off the bottom of the program window

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#38]
(occurs regardless of desktop environment, i.e. it also occurs if you manually install Caja on Cinnamon and/or Xfce)

Note that, while the video only shows newly-created files, this exact issue also occurs with newly-created folders.

[caja.webm](https://user-images.githubusercontent.com/11896003/206620102-2da71c1a-9686-4197-bb6b-a75a9ee1fdbd.webm)

**Comment by NintendoManiac64** [comment]
It would seem that there is a bit more to this issue - the exact same issue happened in my most recent video recording for issue #51 starting at the 3:21 mark despite it being a file created in the middle of the folder.

**Comment by clefebvre** [comment]
Please report to Caja directly.

Note that we'll look into the Nemo issue (hidden folder going "untitled"). If it leads to a fix in Nemo we'll provide a PR for Caja.

https://github.com/mate-desktop/caja/issues
