### ISSUE TITLE
mintwelcome - the option to choose the panel layout is not displayed well

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.1-beta#4]
LM 21.1 beta
![mwelcome](https://user-images.githubusercontent.com/68134588/205496540-d924c5a5-be05-480d-ad07-55c73a387c37.png)

comparing it with LM 21
![21](https://user-images.githubusercontent.com/68134588/205496615-f48a9e73-b63b-4d8c-a340-f8366ce4c150.png)

**Comment by clefebvre** [comment]
hi @haggen88, it was removed on purpose. The look is subject to change, the image needed to be hidpi and they didn't add much to the welcome screen.

**Comment by haggen88** [comment]
@clefebvre  ok I understand.
