### ISSUE TITLE
cinnamon: Fading in of the desktop during boot leaves black artifacts

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint21.1-beta#41]
During the boot process with automatic login, a black screen appears as usual shortly before the desktop is displayed. This is the normal behavior. 
However, the desktop is not displayed evenly, but in individual square sections that appear one after the other. Black areas remain for a short time before the complete desktop is visible. 
I have observed this phenomenon on a laptop since Mint 21 Cinnamon and now in a VM running Mint 21.1 Beta Cinnamon. On the laptop, this only happens when I enable fractional scaling at 125%.
See the following screenshot:
![Desktop](https://user-images.githubusercontent.com/51761218/206712959-72c36481-eb5c-4773-8400-16a89367b9cd.jpg)

**Comment by jakoblm** [comment]
I was able to reproduce it on two devices: The behavior only appears when fractional scaling is active, but also in a virtual machine without fractional scaling.
However, the bug has been occurring since Mint 21 and not just since this beta release.

**Comment by tethragon** [comment]
Do not use fractional scaling in linux mint. It is highly broken. Internally it renders everything at ultra high resolutions, which is a performance hog and a battery destroyer. Furthermore, some websites will run extremely slow because of this. Just use your native resolution and increase font size and icon size from settings in order to achieve the same result. 

Linux mint needs tons of work in order to achieve a serious fractional scaling result

**Comment by clefebvre** [comment]
Cinnamon's fractional scaling is basically the same as Ubuntu's GNOME on Xorg since 5.4.

This looks like a bug in the login desktop effect.

**Comment by mtwebster** [comment]
@jakoblm Does this happen if you disable the startup animation? (Effects settings -> session startup animation)

Thanks

**Comment by jakoblm** [comment]
Yes, I have already disabled all effects in the settings. But it happens with effects turned on and off.

**Comment by jakoblm** [comment]
With fractional scaling I noticed another problem that also exists since Mint 21. When I play a video in mpv and switch to fullscreen mode, the resolution does not fit immediately. When switching to fullscreen, the screen first goes black, then the video appears significantly too large and takes a moment to get the resolution right again. 

When exiting full screen mode, the video appears as four too small individual videos spread across the desktop, it only switches back to normal windowed mode after a few seconds. I hope that I have explained this understandably. By the way, with Celluloid there are no problems. 

I don't know if this bug has the same cause and if we can solve it here?

**Addition**: Redshift status is also ignored when switching full screen mode. Night mode is temporarily disabled until the resolution is correct again.

**Comment by clefebvre** [comment]
Marking this to be fixed later during the dev cycle.

**Comment by jakoblm** [comment]
@clefebvre: That would be great. These limitations are already very annoying. 
Furthermore, fractional scaling causes significant screen tearing when moving windows. As a workaround I had to create this file: `sudo nano /etc/X11/xorg.conf.d/20-intel.conf `

with the following content: 
```
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Option "DRI" "3"
EndSection
```

**Comment by clefebvre** [comment]
Fixed.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/6ff0149f8b3be41bbdb0e1e5aa004564dff89bae
