### ISSUE TITLE
Why are you displaying dates in monospace fonts... 

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.1-beta#42]
... in Nemo?

**Comment by jakoblm** [comment]
This is not the answer to your question, but you can change this again in the Nemo settings.

**Comment by mtwebster** [comment]
Because we thought it was a useful improvement, and it's easier to compare dates between files if they were precisely aligned.

This was mentioned in https://www.linuxmint.com/rel_vera_cinnamon_whatsnew.php
