### ISSUE TITLE
cinnamon: 1.5 text scaling factor causes DPI scaling to enlarge every time Cinnamon is restarted

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#43]
(does not occur on Xfce, and I cannot find any equivalent setting on Mate to test with)

As shown in the below video, this very much occurs beginning with a text scaling factor of _exactly_ 1.5 considering that a text scaling factor of 1.499999999 (eight 9s) does not have the issue occur.

Not shown in the video is that the issue seemingly occurs regardless of how one restarts Cinnamon, including logging out and logging back in.

[dpi.webm](https://user-images.githubusercontent.com/11896003/206775837-725d051c-a30d-4a8a-8361-8b15ccb58a98.webm)

**Comment by clefebvre** [comment]
Confirmed.

At 1.5 font scaling:

- Every hot cinnamon restart with Alt+f2+r or ctrl-alt-escape results in larger fonts
- Every cold cinnamon restart with "cinnamon --replace" does that as well

Logout/login with a new Xorg and cinnamon session goes back to 1.5 and proper scaling.

**Comment by NintendoManiac64** [comment]
It also occurs if you click "Modern" or "Traditional" panel layout in the welcome screen.

**Comment by clefebvre** [comment]
Yes that restarts Cinnamon as well.
