### ISSUE TITLE
mintwelcome - currently-selected buttons are not indicated in any way, making it not very apparent on Cinnamon which 'Panel Layout' setting is the currently-selected one

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#44]
None of the currently selected buttons, such as those used for 'Desktop Colors' and, at least on Cinnamon, particularly 'Panel Layout', have any indication of which button is the currently-selected one.

This means that, due to the images for Cinnamon's 'Panel Layout' settings being removed as stated in #4, it's not very apparent which panel layout is the currently-selected one.  Furthermore, on a lower-quality display with poorer color reproduction (e.g. many older laptops), even the lack of an indication for the currently-active 'Desktop Colors' could be a bit troublesome on Cinnamon/Mate/Xfce since some of the colors may look a bit similar from one-another when shown as just a small square (such as green and teal which are even on opposite ends).

In the screenshot from #4, you can see that there doesn't seem to be a visual difference in button colors or the like between the initially-listed "Aqua" color and any of the others (even though you can clearly see from the program window's accent colors that 'Aqua' is active), as well as there being seemingly no difference in button colors between "Modern" or "Traditional" (even though one of the two obviously must be already selected at any given time).

(and I even checked the screenshot on two very different monitors - a typical office LCD, as well as a CRT with its contrast maxed out but brightness set to minimum)

![screenshot](https://user-images.githubusercontent.com/68134588/205496540-d924c5a5-be05-480d-ad07-55c73a387c37.png)

**Comment by clefebvre** [comment]
This is by design, they're action buttons to paint your desktop. None of them might match you current theme selections.

The dark/light widget is a toggle though, but only because it makes the visual representation easier to understand than having two buttons.
