### ISSUE TITLE
[Cinnamon] mintwelcome - selecting a 'Panel Layout', whether the same or a different one, resets most panel customizations

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#45]
(interestingly, the auto-hide setting does not get reset despite most everything else being reset)

Considering the existence of issue #4 and subsequently issue #44, the user is currently encouraged to experiment and find out for themselves by clicking on either setting to find out which of the two 'Panel Layout' settings they are currently using and whether they'd prefer the other setting.

...which is a problem if it's going to end up resetting all customization as that then encourages the user to _not_ change the setting.  That combined with issue #4 and issue #44 can then lead to the more novice user simply going down the "if it ain't broke, don't fix it" route and not wanting to ever touch it and simply make due with whatever 'Panel Layout' it's set to.

(**tin-foil hat time:** unless the point of this, #4, and #44, is to intentionally get all users to migrate to the "Modern" panel layout with the end-goal of eventually removing the "Traditional" panel layout, in which case I suppose this, along with #4 and #44, are all cases of "it's not a defect, it's a feature!")

[panel.webm](https://user-images.githubusercontent.com/11896003/206794391-9d3d732b-2d00-44c9-a128-eabd66452d03.webm)

**Comment by Nebelfeuer** [comment]
Have also run into this hurdle in the past. Restoring the previous customization when switching back to the previous panel type would definitely be more user friendly.

**Comment by clefebvre** [comment]
The welcome screen is essentially a welcome screen, it's not meant to be used as a customization option once you've grown accustomed to your desktop and tuned it to your liking.

The layouts aren't just panel layouts, they're sets of applets and positions. They necessarily do override your settings.

**Comment by NintendoManiac64** [comment]
> t's not meant to be used as a customization option

It was my impression that the welcome screen is the only way to change the panel layout between modern and traditional - am I wrong?

**Comment by clefebvre** [comment]
It's basically a quick way to tune it the way it was tuned before. There's no such think in Cinnamon as a modern or a traditional layout... there's just an evolution of many defaults, and in Mint we provided a way to set things back the way they were in previous releases, and that's in the welcome screen.

To a new user it makes less sense to have this here. It's really something that is there because some people preferred the previous defaults. Eventually it should probably go.

From a Cinnamon's point of view the job is to make it easy to tune anything, but there are no set layouts.

**Comment by haggen88** [comment]
@clefebvre  Is it normal that the corner bar disappears when the Traditional panel layout is selected?

**Comment by clefebvre** [comment]
Yes, the traditional layout uses a show-desktop applet near the menu.
