### ISSUE TITLE
When saving a file, if you type a different file name and then click 'Home' in the left-side bar (or 'Desktop' if it defaulted to 'Home'), a drop-down menu appears under the file name before saving

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#46]
Note that this occurs on Cinnamon, Mate, and Xfce, but it seemed redundant to show it on all three environments when repeating the issue can be done using the exact same steps regardless of desktop environment.

[video.webm](https://user-images.githubusercontent.com/11896003/206810502-1aca9200-9406-4307-b7a8-d013d9f9a725.webm)

**Comment by mtwebster** [comment]
This isn't a Mint issue - the toolkit (gtk) provides that dialog. And I'm not really sure that's even a bug - it's trying to autocomplete for you. When you change folders it triggers that again.

I guess it probably shouldn't if there are no matches in the new location, but we can't do anything about it regardless.
