### ISSUE TITLE
simple-scan: In preferences, widgets for 'Enable Postprocessing' and 'Keep Original File' don't toggle properly

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#47]
(this occurs on Cinnamon, Mate, and Xfce, but I'm just showing it on Xfce since that's my preferred desktop environment and the steps are identical for replicating this issue on Cinnamon and/or Mate)

[video.webm](https://user-images.githubusercontent.com/11896003/206814424-c177fc90-59ce-4b5b-b2f6-dddcba3167fd.webm)

**Comment by clefebvre** [comment]
That's a funny bug :)

Please report it upstream at https://gitlab.gnome.org/GNOME/simple-scan/-/issues
