### ISSUE TITLE
mintstick: issues with themes other than Mint-Y

### ISSUE THREAD

**Issue by jbergengh** [linuxmint/mint21.1-beta#48]
In Themes, set the Icon Theme to Adwaita, Breeze, ePapirus, Highcontrast, Papirus,  or Breeze dark.
Format a USB stick using USB Stick Formatter.
When mintstick notifies you that stick has finished formatting, note the Information icon is broken or missing.

In Themes, set the Application Theme to Adwaita, Hicontrast or Mint-X
Format a USB stick using USB Stick Formatter.
While the stick is formatting, note that the progress bar is not displayed properly. The pulsing color bar is missing its color (Mint-X) or is missing entirely (Adwaita & Highcontrast)

The Mint-Y theme works properly in both cases.

**Comment by clefebvre** [comment]
Fixed in mintstick 1.5.3
