### ISSUE TITLE
cinnamon: traditional panel, 1.75 text scaling factor,  panel height of 32-47, a folder named ".$ settings" (without quotes) results in labeling issues

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#49]
(only occurs on Cinnamon, albeit with Nemo, Caja, or Thunar)

Not shown in the video (it's admittedly lengthy＊) is that it doesn't *only* occur with a text scaling factor of 1.75, but it seems to work best with that (it also somewhat works with a value of 1.76 for example)

To be clear, this isn't a graphics driver issue either as it occurs on both a Radeon HD5450 on real hardware and through VirtualBox running on Intel Haswell integrated graphics.

**EDIT**: I realized something about the panel text behavior - when it's only showing `.$ set|`, if you do not hover your cursor over the panel and click back, it'll display `Home` on the panel without issue - it only displays `Home:ings` if you previously hovered your mouse cursor over the `.$ set|` (this is why, beginning at the 11:07 mark in the video, Thunar displayed `Home` on the panel without issue)

[10MB test.webm](https://user-images.githubusercontent.com/11896003/206883019-91f33717-9e32-4fe7-9415-f4e0f34a64eb.webm)

＊I kind of wanted to see just how much footage and fidelity could be retained within github's 10MB limit, so I basically showed every single combination I could think of.  Needless to say, the fidelity isn't great, but it did work.

**Comment by clefebvre** [comment]
Does restarting Cinnamon solve the issue ?

**Comment by NintendoManiac64** [comment]
> Does restarting Cinnamon solve the issue ?

It's a bit of a pain to say since restarting Cinnamon with 'Text scaling' set to greater than 1.5 then results in issue #43 and that same issue means that the order of operation on replicating this issue is *very* important - setting the panel to traditional *after* setting 'font scaling' will have you run into issue #43 as soon as you click "Traditional" panel layout.

**Comment by clefebvre** [comment]
rofl, this is excellent :)

**Comment by NintendoManiac64** [comment]
How else did you think I discovered these issues in the first place? :P  You wouldn't imagine how many times, when when working on narrowing-down and replicating an issue, that I end up discovering other issues in the process...

Anyway, it was a bit difficult, but I managed to restart Cinnamon and, yes, the issue persists.

I did just realize something about the panel text behavior - when it's only showing `.$ set|`, if you do *not* hover your cursor over the panel and click back, it'll display `Home` without issue - it only displays `Home:ings` if you previously hovered your mouse cursor over the `.$ set|`

**Comment by mtwebster** [comment]
I can sort of reproduce this - this ghosting/flickering issue has been around forever (years and years) and I think it's partially a graphics hardware problem, so I'm not sure what can be done about it.

**Comment by NintendoManiac64** [comment]
> I think it's partially a graphics hardware problem

Really? Even though, as I stated, I originally discovered it on a Radeon HD5450 and my video is of it running in VirtualBox on Intel Haswell (4th gen Core) integrated graphics?

If you really insist that it's hardware, then that's one thing I definitely have much more expertise in - that is, I have *lots* of hardware on-hand that I can test this with (my amount of Nvidia hardware is lacking though for obvious non-friendly-to-Linux reasons, but I have a lot of AMD GPUs and a good amount of Intel integrated graphics).

**Comment by mtwebster** [comment]
I know it's not particular to any specific brand (it happens for me on intel an nvidia), but I've dug into it more than once in the past, and it's not caused by anything in our code, as far as I know (plus it's survived a *major* update to the graphics library Cinnamon uses - clutter). More of a buffer problem maybe.

**Comment by mtwebster** [comment]
It occurred to me it might be two shapes being painted on the same actor, I wish I could reliably reproduce this.
