### ISSUE TITLE
Cinnamon - nemo 'Folder Colour Switcher' does not change icon colours correctly

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/mint21.1-beta#53]
The 'Folder Colour Switcher' does not change icon colours correctly:-
Only the thin diagonal sliver is changed, which effectively causes the colour switcher to have no purpose.

**Comment by mtwebster** [comment]
Support for legacy icons has been fixed in git:
https://github.com/linuxmint/folder-color-switcher/commits/master

However, like always, the current theme is used to choose icons from, so it would make sense for only the strip to change if that's the current theme.
