### ISSUE TITLE
[Mate] Copying a lot of files onto the desktop results in them being "sorted" (if you can call it that) with extreme disarray

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#56]
(only occurs on Mate)

Interestingly, as shown in the video, the aforementioned disarray only seems to occur if you drag-and-drop or do a copy then paste rather than a `copy to` **→** `Desktop`

[mate desktop copying files.webm](https://user-images.githubusercontent.com/11896003/206887530-fe7d18d2-df57-40e5-9e74-78dd3b5de5e5.webm)

**Comment by clefebvre** [comment]
This looks like an upstream bug. Please report it to caja directly.

https://github.com/mate-desktop/caja/issues
