### ISSUE TITLE
[Mate] After copying a lot of images onto the desktop, disabling then re-enabling "Keep aligned" results in super-tightly packed-together files and, after logging out then logging back in, the alignment still doesn't perfectly match what it should be

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#57]
(only occurs on Mate)

[mate desktop icon alignment.webm](https://user-images.githubusercontent.com/11896003/206887854-dfe4a7e2-1660-4ae1-8913-531f65941935.webm)

**Comment by clefebvre** [comment]
This one is upstream and part of Caja (Caja handles both the file manager and the desktop files managements).

https://github.com/mate-desktop/caja/issues
