### ISSUE TITLE
[Mate] Delayed result and high CPU usage both during and after opening "Change desktop background"

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#58]
Now admittedly both Cinnamon and Xfce also depict high CPU usage while rendering in the backgrounds, but Mate takes substantially longer to even show *any* files, and it keeps having high CPU usage even after the files have finally displayed.

[mate high cpu backgrounds.webm](https://user-images.githubusercontent.com/11896003/206888024-87581e80-5d04-4b00-b93c-049c743300bf.webm)

**Comment by clefebvre** [comment]
It renders them synchronously. The more artwork we ship the more it struggles. This is upstream and should be reported to MATE under mate-control-center.

https://github.com/mate-desktop/mate-control-center/issues
