### ISSUE TITLE
Keyboard doesn't work on Lenovo Yoga slim 7i pro

### ISSUE THREAD

**Issue by zoenr** [linuxmint/mint21.1-beta#59]
Laptop keyboard does not work  on Lenovo Yoga slim 7i pro. Note that external keyboards do work, just not keyboard that's part of the laptop. Seems to be fixable by editing grub as specified here: https://askubuntu.com/questions/1352604/ubuntu-20-04-keyboard-not-working-on-lenovo-yoga-slim-7i-pro

**Comment by clefebvre** [comment]
Sorry to hear @zoenr. I added a section in the release notes for other people to find the info more easily.
