### ISSUE TITLE
mintinstall: uninstalling a flatpak doesn't remove unused runtimes

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.1-beta#6]
steps to follow
1) install a flatpak app
2) uninstall  such an application

- app installed:
![A1](https://user-images.githubusercontent.com/68134588/205518543-9718e5c5-5392-4631-934e-20f85046f41f.png)
- app uninstalled:
![A2](https://user-images.githubusercontent.com/68134588/205518547-acffa8fe-9276-43e6-bf2a-4afacfebc0dc.png)

After uninstall the application, the runtimes and extensions remain [taking up space].  It would make sense that they would remain when using apps that share them, but mininstall does not uninstall the apps correctly.

Maybe it would be good to include '**flatpak uninstall --unused**' in mintinstall.

![3](https://user-images.githubusercontent.com/68134588/205525945-75b069e1-858b-4d46-b650-cdfedadecaff.png)

**Comment by mtwebster** [comment]
I partly agree - 

I think maybe EOL'd runtimes should be autoremoved but not active ones. They can take quite a bit of space but they can also take forever to download. If I remove some flatpak, then in the same session add a different one, that might mean re-downloading a runtime I just removed, and another 5-10 minute wait.

Maybe in the future we can add some flatpak maintenance tasks to our housekeeping process to look at unused (non-EOL'd) runtimes (right now it only removes old screenshots).

edit: We can definitely clean up app-specific runtimes as well (addons, etc..).

**Comment by haggen88** [comment]
@mtwebster  I understand, it's a valid [approach](https://blogs.gnome.org/mwleeds/2021/01/11/cleaning-up-unused-flatpak-runtimes) . Otherwise the redesign of Software Manager is great!

--

BTW a doubt ... is it normal for an icon theme to change the flatpak symbolic icon in mintinstall?. This happens with Numix-circle.

![numix circle flatpak symbolic](https://user-images.githubusercontent.com/68134588/205775529-14c8034a-4002-474c-9f13-73c503f7e4aa.png)

![2](https://user-images.githubusercontent.com/68134588/205778045-a6c37402-6614-47b4-8cbb-4175300fe2f0.png)

**Comment by mtwebster** [comment]
Thanks, glad you like - as for the icon, I hadn't really considered it. Personally I'd probably want these to stay the same just so the look was consistent here and in mintupdate. We had no symbolic flatpak icon, all the Mint themes have is the mimetype icon.

That one Numix is using is named simply 'flatpak' - it shouldn't be selected over ours in the first place, but that's how Gtk icon themes work now I think. I'll fix it, thanks.

**Comment by mtwebster** [comment]
Just fyi, we're already automatically removing unused runtimes in mintupdate as of https://github.com/linuxmint/mintupdate/commit/1fcf10dbe10d38f7fe01ad30b5d58f5115def4ee

In hindsight, maybe that's a bit too aggressive, but, on the other hand, no one's complained about it, so not touching it at this time.
