### ISSUE TITLE
Just a suggestion: Choice of sounds

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/mint21.1-beta#60]
I like the Material Design sounds, they feel very refreshing and nice. But I think the actual sounds you picked aren't the best. I have some ideas that I use for my setup in 21.0. I will list them by their original filename in the Material Product Sounds archive. Sorry for the descriptions, I have my system set to Romanian, but they're in the same order as in the settings page.

Login - ui_loading.ogg
Logout - navigation-cancel.ogg
Switch workspace - navigation_transition-right.ogg
Map windows - ui_refresh-feed.ogg
Close windows - navigation_unavailable-selection.ogg
Minimise windows - navigation_backward-selection-minimal.ogg
Maximise windows - ui_lock.ogg
Restore windows - ui_unlock.ogg
Window tiling - ui_tap-variant-03.ogg (should also be disabled by default, the other window sounds are disabled by default so why should this one not be)
Insert device - state-change_confirm-up.ogg
Remove device - state-change_confirm-down.ogg
Show notifications - navigation_forward-selection.ogg
Change sound volume - navigation_backward-selection.ogg

**Comment by clefebvre** [comment]
Thanks for the feedback @Secret-chest. I'm not sure what to say, it's definitely a subjective choice..

**Comment by Secret-chest** [comment]
> Thanks for the feedback @Secret-chest. I'm not sure what to say, it's definitely a subjective choice..

I know. Just wanted to leave my ideas and thanks for your amazing work, Linux Mint is so pleasant to use, and even more so knowing the people behind it actually care (about their users, not their money) and there's no corporate.

**Comment by clefebvre** [comment]
Thanks @Secret-chest, you just made my day :)
