### ISSUE TITLE
Order of icon themes is confusing

### ISSUE THREAD

**Issue by the-allanc** [linuxmint/mint21.1-beta#64]
Icon themes seem to be grouped in "light" (from Adwaita to Yaru-viridian), and then dark (from breeze-dark to Yaru-viridian-dark).

And then all the Mint-Y-Legacy icons are at the end, both light and dark. The same thing appears to be happening with the Application themes.

**Comment by clefebvre** [comment]
This is done on purpose to have color variants of the same theme side by side.

**Comment by the-allanc** [comment]
> This is done on purpose to have color variants of the same theme side by side.

Except @clefebvre... it isn't?

For example, in icons, between the light and dark variants of Papirus, we have:

- Light Yaru themes
- Dark Breeze theme
- Dark ePapirus theme
- Dark Mint-X themes
- Dark Mint-Y themes

The variants of the Papirus themes aren't all together. Which is fine if we're grouping light themes together, and then dark themes (which seems to be the case), but then you have the Mint-Y-Legacy themes at the very end (both light and dark). So it's:

- All light themes (except Mint-Y-Legacy)
- All dark themes (except Mint-Y-Legacy)
- All Mint-Y-Legacy themes

Which appears to be inconsistent.

**Comment by clefebvre** [comment]
Have a look at Cinnamon 5.4. Before we moved legacy and dark aside, they were all getting mixed up (light, dark, legacy) and sorted alphabetically. You'd typically get some colors like Blue, Brown, then Dark colors, then at some stage Legacy ones.. and then eventually Red, Sand, Teal...

**Comment by the-allanc** [comment]
@clefebvre I understand the motivation for the change, but I think we've got crossed wires here.

You're saying the sorting mechanism was: "_Order by name_"
And now it's "_Order by light/dark, then order by name_".

Except it isn't, it appears to be "Order by whether it is not Mint-Y-Legacy, then order by light/dark, then order by name".

**Comment by clefebvre** [comment]
> it appears to be "Order by whether it is not Mint-Y-Legacy, then order by light/dark, then order by name".

That's what it is.

Legacy are at the bottom, they're a like a section to themselves. And light and dark are also separated.
