### ISSUE TITLE
Too many "Mint-Y" variants in themes

### ISSUE THREAD

**Issue by the-allanc** [linuxmint/mint21.1-beta#65]
If I've counted correctly, there are now 44 "Mint-Y" themes for applications, icons and desktop. I feel like that is too many variations of what is apparently the same theme - especially in the Desktop section when there are a lot of very similar looking previews.

While I know there is some discussion about the choice of themes and what the defaults are (like in #28), I think it would be sensible to reduce the amount of choices, and maybe make them available as optional installs.

Other options which might help is to rename the new themes as something else ("Mint-Z"?) or change the theme chooser to group related themes into sections.

**Comment by Mr-Dead** [comment]
Hello.
Here is one noticeable consequence of theme bloat: qt5ct taps out cpu for over 20 seconds while loading themes.
![qt5ct_spike](https://user-images.githubusercontent.com/2031616/206922276-26bcd8ec-35e3-4fc2-b9a0-a9c8127fcf19.png)

![qt5ct_spike_done](https://user-images.githubusercontent.com/2031616/206922282-445d116b-c441-4919-9b7d-f41d90ad694a.png)

```
System:
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0
    Desktop: Cinnamon 5.6.4 tk: GTK 3.24.33 wm: muffin dm: LightDM 1.30.0
    Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: Micro-Star product: GT70 2PE v: REV:0.C
    serial: <filter> Chassis: type: 10 serial: N/A
  Mobo: Micro-Star model: MS-1763 v: REV:0.C serial: <filter>
    UEFI: American Megatrends v: E1763IMS.51D date: 04/17/2015
Memory:
  RAM: total: 15.55 GiB used: 2.69 GiB (17.3%)
  Array-1: capacity: 32 GiB slots: 4 EC: None max-module-size: 8 GiB
    note: est.
  Device-1: ChannelA-DIMM0 size: No Module Installed
  Device-2: ChannelA-DIMM1 size: 8 GiB speed: 1600 MT/s type: DDR3
    detail: synchronous bus-width: 64 bits total: 64 bits manufacturer: Crucial
    part-no: CT102464BF160B.C16 serial: <filter>
  Device-3: ChannelB-DIMM0 size: No Module Installed
  Device-4: ChannelB-DIMM1 size: 8 GiB speed: 1600 MT/s type: DDR3
    detail: synchronous bus-width: 64 bits total: 64 bits
    manufacturer: Kingston part-no: MSI16D3LS1KBG/8G serial: <filter>
CPU:
  Info: quad core model: Intel Core i7-4810MQ bits: 64 type: MT MCP
    smt: enabled arch: Haswell rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 2794 high: 2795 min/max: 800/3800 volts: 1.2 V
    ext-clock: 100 MHz cores: 1: 2794 2: 2793 3: 2794 4: 2794 5: 2794 6: 2795
    7: 2794 8: 2794 bogomips: 44692
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel 4th Gen Core Processor Integrated Graphics
    vendor: Micro-Star MSI driver: i915 v: kernel ports: active: eDP-1
    empty: VGA-1 bus-ID: 00:02.0 chip-ID: 8086:0416 class-ID: 0300
  Device-2: NVIDIA GK104M [GeForce GTX 880M] vendor: Micro-Star MSI
    driver: nvidia v: 470.161.03 pcie: speed: 2.5 GT/s lanes: 16
    bus-ID: 01:00.0 chip-ID: 10de:1198 class-ID: 0300
  Display: server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 98 s-size: 499x280mm (19.6x11.0")
    s-diag: 572mm (22.5")
  Monitor-1: eDP-1 model: LG res: 1920x1080 hz: 60 dpi: 128
    size: 382x215mm (15.0x8.5") diag: 438mm (17.3") modes: 1920x1080
  OpenGL: renderer: Mesa Intel HD Graphics 4600 (HSW GT2)
    v: 4.6 Mesa 22.0.5 compat-v: 3.1 direct render: Yes
Drives:
  Local Storage: total: 1.14 TiB lvm-free: 19.75 GiB used: 26.37 GiB (2.3%)
  ID-1: /dev/sda vendor: Samsung model: SSD 840 EVO 250GB size: 232.89 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: BB6Q scheme: GPT
  ID-2: /dev/sdb vendor: Crucial model: CT1000BX500SSD1 size: 931.51 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: 054



```

**Comment by haggen88** [comment]
There really are a lot of variations...   It's not something that bothers me in particular, but if you want to keep the large number of options I suggest improving the way to navigate them.  The current configuration [up and down button] could be upgraded to a scroll bar.

**Comment by mdevansh06** [comment]
There are two packages for mint-y themes. One is mint-themes and other is mint-themes-legacy. You can remove mint-themes-legacy if you do not want mint-y-legacy themes. This package has themes from about two releases back for preserving them .

**Comment by Nebelfeuer** [comment]
I like the options but perhaps a more compact way of presenting them: like a single dark/light theme (and maybe modern/legacy in case of mint-y) variant toggle could help?

**Comment by mdevansh06** [comment]
mint-y legacy is a different package, it can be removed if you like. 
I don't know if it is present in a default install ootb

**Comment by mdevansh06** [comment]
> I like the options but perhaps a more compact way of presenting them: like a single dark/light theme (and maybe modern/legacy in case of mint-y) variant toggle could help?
mint-y legacy is a different package, it can be removed if you like.
I don't know if it is present in a default install ootb

**Comment by mdevansh06** [comment]
> I like the options but perhaps a more compact way of presenting them: like a single dark/light theme (and maybe modern/legacy in case of mint-y) variant toggle could help?


Mint-y legacy is present in a completely different package.
I do not know if it is present in default install OOTB.

**Comment by clefebvre** [comment]
We might redesign theme selection in Cinnamon 5.8.

We're also likely to remove legacy themes from the default installation in the future, but not right now. They're here to show people we still support the old look, especially since we're just after changing it.

**Comment by LinuxOnTheDesktop** [comment]
> We might redesign theme selection in Cinnamon 5.8. // We're also likely to remove legacy themes from the default installation in the future, but not right now. They're here to show people we still support the old look, especially since we're just after changing it.

Given the count of

> 44 "Mint-Y" themes

I think that at least one of those 'mights' should be a 'will' (if I may say so).

**Comment by Secret-chest** [comment]
> I like the options but perhaps a more compact way of presenting them: like a single dark/light theme (and maybe modern/legacy in case of mint-y) variant toggle could help?

What about other themes?

**Comment by Secret-chest** [comment]
> We might redesign theme selection in Cinnamon 5.8.

Some of my points:
* Don't support Mint themes better. Maybe add an API for themes to add info about them so they can be shown as a single listing?
* Please don't group themes and icons: some themes may not have icons or viceversa, what would happen? Same goes for icons and cursors.
* Yes, do add a scrollbar and make the theme selectors separate windows, please!
* What are those scrollbar settings doing? Shouldn't they be in the Windows applet?

**Comment by mdevansh06** [comment]
A theme and icon selector similar to that in Plasma will be good, while still providing previews for themes and icons.

imo, there should be dialog boxes or separate windows for these things, not lists with scroll buttons.

**Comment by Secret-chest** [comment]
> imo, there should be dialog boxes or separate windows for these things, not lists with scroll buttons.

That's what I said.

**Comment by Secret-chest** [comment]
> A theme and icon selector similar to that in Plasma will be good, while still providing previews for themes and icons.

My concerns are that some themes don't have icons or viceversa.

**Comment by mdevansh06** [comment]
@Secret-chest I did not say icons merger with themes.

What i meant was icons separated from themes, even if themes have icons, with an indication to tell if a theme has matching icons. If it does not, no such indicator be shown.
