### ISSUE TITLE
mintwelcome: changing the desktop theme changes the theme of the icons

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.1-beta#68]
steps to reproduce

1- choose an icon theme [other than those designed for Mint] for example 'Papirus'
2- open mintwelcome and switch from light to dark desktop theme

[mintwelcome-change-icons.webm](https://user-images.githubusercontent.com/68134588/206923306-0849296c-7858-4622-87c7-cabd646d8616.webm)

It also happens when you go from a dark theme to a light one or when you choose a color.

[select-colour.webm](https://user-images.githubusercontent.com/68134588/206931174-25e05f9b-0700-4dfb-8fbe-509622ffae42.webm)

-

Perhaps [as for Panel Layout] a note should be added explaining that changing the desktop theme and colors will change the icon theme.

**Comment by clefebvre** [comment]
This is by design. Choosing a favorite color in the welcome screen sets a whole lot of matchy-matchy things for you.

In the Cinnamon themes settings you're getting to a more granular level. By then you're done with the first step in the welcome screen.
