### ISSUE TITLE
[Cinnamon] Highlight on mouse-over for a disk does not separately highlight the text label and the unmount / eject icon, making it unclear where one function ends and the other one starts

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#69]
(Mate and Xfce do not have the highlight on mouse-over, therefore this only occurs with Cinnamon)

The text label for a drive and the unmount / eject icon are not highlighted separately which makes it difficult to tell where one function ends and the other begins.

[eject.webm](https://user-images.githubusercontent.com/11896003/206948192-52d4de77-3917-435a-92cb-a9c6bf8a48d7.webm)

**Comment by clefebvre** [comment]
The video doesn't seem to work. Are you talking about the nemo sidebar eject icon?

**Comment by NintendoManiac64** [comment]
> The video doesn't seem to work.

Are you sure?  It was encoded identically to the other videos I've posted and it's working just fine in the Firefox that is provided in the live ISOs for Mint 20.3, Mint 21.0, and Mint 21.1, and it also works when downloaded and played through the Celluloid provided in the live ISOs for Mint 20.3, Mint 21.0, and Mint 21.1.

Nevertheless, here's an AVC mp4 directly re-encoded from the aforementioned WebM (so it'll *technically* be lower fidelity due to lossy--to->lossy transcoding) hosted on the temporary file host recommended by the mpv devs (mind the capitalization):

- http://0x0.st/onNV.mp4

> Are you talking about the nemo sidebar eject icon?

That as well as the "safely eject" pop-up menu located on the panel.

**Comment by clefebvre** [comment]
The video works now.

The sidebar icon is in Nemo.
The applet icon is in Cinnamon.

Both issues are similar. We need to make these react to hover theme-wise or give them a border.

**Comment by clefebvre** [comment]
We'll look at this in the next dev. cycle.
