### ISSUE TITLE
artwork: Use Aqua theme variant for greeter?

### ISSUE THREAD

**Issue by bobby285271** [linuxmint/mint21.1-beta#7]
mint-artwork 1.7.2

I know I can configure everything in `/etc/lightdm/slick-greeter.conf`, but I am just curious why the rest of the desktop is now using the Aqua theme variant (Mint-Y-Aqua) the greeter is still using the green theme variant (Mint-X)? (I assume this is set in `mint-artwork.gschema.override`, it is fine if this is by design, I am just curious :see_no_evil:).

![](https://user-images.githubusercontent.com/20080233/205636529-967cc12f-8f30-47ca-b4ab-677e74842354.png)

**Comment by carlosmintfan** [comment]
Why did they port it to Aqua at all? In Vanessa, the standard color is green...

**Comment by clefebvre** [comment]
thanks @bobby285271 it's an oversight.

**Comment by clefebvre** [comment]
Fixed in mint-artwork 1.7.3.
