### ISSUE TITLE
cinnamon: Settings icons look like Mint-X

### ISSUE THREAD

**Issue by bkovacs007** [linuxmint/mint21.1-beta#71]
The only issue I have so far is when using the Cinnamon edition, when you apply the Yaru or Breeze icon set. The "Settings" icon and icons within setting remain Faenza icons. They don't change. I believe that isn't the case with the Mate edition. It would also be nice if we had a Yaru and Breeze taskbar theme for the Cinnamon edition. Stays the same on logging out and logging back in as well.

**Comment by clefebvre** [comment]
That's a good point. That's because Cinnamon ships with icons which look like Mint-X.

Ideally it should ship with generic icons and Mint-X should override them.

This won't get fixed in this release but I'll add it to the roadmap for 21.2.
