### ISSUE TITLE
Missing mouse button debouncing leads to horrible user experience for people coming from windows

### ISSUE THREAD

**Issue by momo42** [linuxmint/mint21.1-beta#72]
This ongoing Linux (and Linux Mint) problem has been discussed in several forum threads and blog comments over the last years. One user brought it up again in the November blog post:
https://blog.linuxmint.com/?p=4438#comment-334519

It seems that the Linux mouse driver (unlike the windows one) lacks a proper debouncing feature. Many users report that their mice often do unwanted double clicks, second clicks while releasing the mouse button and release-click sequences for example while dragging files around. While this looks like a hardware issue with worn out micro switches also many brand new mouse models are affected. For example Logitech wireless mice m185 and m190 as described in the blog post above. I'm personally affected with a brand new Logitech m185. Many cheap models are affected but also some expensive ones. All have in common, that switching back to windows magically solves all problems. While bouncing hardware buttons are clearly a hardware flaw, manufacturers seem to ignore bouncing detection on the hardware side because debouncing is already perfectly handled in the windows driver.

I understand, that this is an upstream problem but one other user in your blog stated and I also found that upstream bug reports regarding the lack of proper debouncing have been constantly ignored for the last 15 years:
https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-libinput/+bug/602809
https://bugs.freedesktop.org/show_bug.cgi?id=11833

To be clear: This has nothing to do with double click speed setting.

In my case I switched my parents' computer from windows 8.1 to Linux Mint 21 and some days later my parents said while they liked the new os their mouse just broke and drives them crazy with ghost clicks. So I bought another one of the same kind but the effect stayed the same. Putting the old Windows 8.1 harddrive back into to machine solved all the problems immediately. There has no special manufacturer mouse driver been installed on windows. I also tested the mice on my own Linux Mint 21 machine (and on Mint 21.1 beta) and can confirm these issues indeed drive you crazy. Moving Files via drag and drop is like gambling. Context menus do crazy things and sometimes you even don't get what has been clicked accidentally.

This might be out of scope for the Mint 21.1 release but please have a look into it! This bug not just ruins the user experience of many new linux users but also produces piles of e-waste year by year.

**Comment by NintendoManiac64** [comment]
The irony of course is that the newer optical switches wouldn't need any sort of debouncing support (and such a thing would actually unnecessarily increase their input lag, and lower input lag is the other key benefit of optical switches).

So basically this issue has gone on long enough that it's getting to the point that we already have the next generation of hardware that's coming about that will make it all a moot point anyway.

**Comment by clefebvre** [comment]
If evdev makes this configurable we could consider adding support for it in Cinnamon.

In the meantime this is definitely upstream though.
