### ISSUE TITLE
nemo: toggle button disappear in entry-only mode

### ISSUE THREAD

**Issue by Nebelfeuer** [linuxmint/mint21.1-beta#73]
LM 21.1 beta live usb
The idea behind the new behavior is good, but the execution still need a little work.
Currently the optional toggle-button vanishes once you switch from the path-bar to the entry-bar. Meaning there is no one-click solution to switch back to the path bar when the entry bar is your preferred default. instead you have to use a keyboard shortcut or the view-menu. This is confusing and unnecessarily complicated.

Possible solution: keep the new (auto-switching) behavior for double-clicking the path bar but revert the (optional) toggle button back to it's former behavior as a permanent toggle-switch and display it in both modes of the bar again.

Another option would be to put a checkbox into the settings that allows you to select between the old and new behavior although I would consider that somewhat less elegant then the aforementioned solution.

**Comment by princepaul** [comment]
1. Did you try escape button to get the path bar back?
2. Did you enable Location Entry Toggle in the Nemo > Preferences > Toolbar?

**Comment by mtwebster** [comment]
Some further explanation on how it works and our thoughts behind it: 
https://github.com/linuxmint/nemo/issues/3134#issuecomment-1345348258

> Another option would be to put a checkbox into the settings that allows you to select between the old and new behavior although I would consider that somewhat less elegant then the aforementioned solution.

More options isn't really an option here. The idea of this is to make the automatic behavior appealing to everyone. It's fairly common behavior as well with other file managers.

I'm not trying to be defensive here - I just haven't heard compelling arguments *why* yet, just that things are different (and maybe not well-explained or discoverable).

**Comment by NintendoManiac64** [comment]
I think the most elegant solution would be to simply have the behavior inverted when you have View -> Toolbar  set to "Location Entry".

In other words, it would default to location entry and then, if you click the button (that is currently not visible due to a possible bug), then it will switch to "Path Bar" mode; when you navigate to a different location, it would then automatically switch the current view back to "Location Entry".

**Comment by mtwebster** [comment]
I'm an idiot I got the issue links reversed in the commit message:
https://github.com/linuxmint/nemo/commit/003e516cdaadd9a7d5ce0031c0280f2e51b779e0
