### ISSUE TITLE
Small color coding problem with the new folder design

### ISSUE THREAD

**Issue by Nebelfeuer** [linuxmint/mint21.1-beta#75]
2  of these 10 folders are colored differently(8x blue, 1x teal and 1x aqua) can you tell which ones?
![Screenshot from 2022-12-12 22-05-38](https://user-images.githubusercontent.com/120382643/207168293-0f876650-5441-481c-9585-eccf2b61b5e7.png)

If you guessed 'Pictures' for aqua and 'Templates' for teal you are right('Desktop is set to blue btw.), but I guess the picture demonstrate quite, well that the placement and size of the colored ribbon (although it looks very nice!) could use some more thought in order for color coding to make any sense outside of pure decoration.

**Comment by clefebvre** [comment]
Feedback received :)

We'll improve on that in the future.

https://github.com/linuxmint/mint21.1-beta/issues/28 
https://github.com/linuxmint/mint-y-icons/issues/327
