### ISSUE TITLE
Glitch in the wait animation of the Bibata cursors

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint21.1-beta#76]
I've noticed some glitches at the end-of-the-cycle animation on the Bibata cursors.

There are some GIFs to exemplify it:

* Bibata Modern
![Peek 2022-12-12 20-31](https://user-images.githubusercontent.com/63073056/207241431-47520b04-d42c-470f-bbdd-904517bf264f.gif)

* Bibata Original
![Peek 2022-12-12 20-33](https://user-images.githubusercontent.com/63073056/207241582-498fed94-b6d1-4b0c-927c-7f3f2d3148ca.gif)

---

To confirm this I went to your fork of the Bibata repository and analyzed the bitmaps generated, my conclusions are below.
  
### Bibata Modern

These are the first two images of the wait animation:
![wait-0001](https://user-images.githubusercontent.com/63073056/207242596-6aa27f05-96e7-462d-959e-9f4fe7e5ab27.png) ![wait-0002](https://user-images.githubusercontent.com/63073056/207242612-e01df998-0cb3-4520-8039-c8ef8b91d346.png)

And these are from the number 195 to the last one:
![wait-0195](https://user-images.githubusercontent.com/63073056/207242902-f9532c83-b024-434a-8efc-609723e0c52f.png) ![wait-0196](https://user-images.githubusercontent.com/63073056/207242947-dd3ca9af-d5d3-4383-bfc0-77b16f191d76.png) ![wait-0197](https://user-images.githubusercontent.com/63073056/207242966-a62db088-c211-4724-ac3f-dc2fc62454fb.png) ![wait-0199](https://user-images.githubusercontent.com/63073056/207243265-f248f028-00a3-4c14-92f4-52d2771d26d6.png)

If you noticed from 195 on, the images make a small comeback in their movement, to then return to the same position as the one in 195. I believe that's causing that small glitch on the bibata modern cursors.

### Bibata Original

With the bibata original cursor, the problem is more noticeable in the middle of the animation. The next images are images of numbers 165 and 166 of the wait animation:
![wait-0165](https://user-images.githubusercontent.com/63073056/207245283-31516b58-c227-4523-a64e-4397ca4e786d.png) ![wait-0166](https://user-images.githubusercontent.com/63073056/207245301-2514d4b1-6e8d-4b27-a422-72d82dad3772.png)

As you may see, it takes a huge step from the first one (corresponding to the bitmap number 165) to the second (corresponding to the 166).

---
Well, I don't believe this is a release blocker, but it feels kind of strange after you notice it the first time. :)

**Comment by clefebvre** [comment]
Thanks @anaximeno, please report it upstream directly: https://github.com/ful1e5/Bibata_Cursor/issues.
