### ISSUE TITLE
Window widget style is controlled by icon theme instead of window theme

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/mint21.1-beta#78]
The Mint 21 Cinnamon theming bug still exists, where the window widget style (aka the minimize, maximize, and close buttons in the top right corner of the window) is set by the icon theme and not the window theme. This makes window theming very inconsistent. Windows that use the same standards as Cinnamon will show the icon theme version of the window widgets, while other themes (such as some Gnome-based applications) will show the widgets as they should look according to the window theme. Ideally, they should be controlled by the window theme, and not the icon theme setting.

**Comment by Initu-Castilhos** [comment]
This problem bothers me too, I use Papirus-Green with Min-Y theme.  I copy the minimize, maximize and close icons from Mint-Y in Papirus to be consistent with the gtk theme.

**Comment by biki28** [comment]
This looks really bad. From mint 21 the window control buttons are handled by the icon theme but for some icon themes(maybe for those icon themes which don't support window controls) it looks really bad. For example in numix- This button layout applies to papirus and adwaita too but for the case of yaru they are stuck with mintY buttons and for others like breeze or ePapirus they are using their own which looks good.
Maybe for this case the icon theme numix, paiprus they can use the minyY control buttons like yaru. Can this be implemented in this beta phase?
Thank you for the amazing work.

**Comment by clefebvre** [comment]
I want to get that fixed. It's there since the mutter rebase indeed afaik. It's not a blocker but we'll look at it during the cycle. I'm marking it accordingly and closing it.
