### ISSUE TITLE
Mozilla Firefox freezes unexpectedly

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.1-beta#79]
Testing the beta [live USB] it has repeatedly happened to me that the Firefox 107.0.1  window freezes randomly, I thought it was a memory problem or a Live USB problem. I installed the beta on a VM but the problem happens again. No CPU overload or out of memory issues.

Seems to be this [problem](https://forums.linuxmint.com/viewtopic.php?f=47&t=376770) and  apparently version 102.6 ESR/ [108.0 corrects it](https://bugzilla.mozilla.org/show_bug.cgi?id=1781167)

**Comment by clefebvre** [comment]
108.0 went live yesterday so I'll close this.
