### ISSUE TITLE
nemo: actions with quotes in the Exec line fail when a target file's path contains spaces.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.1-beta#8]
via USB image writer works correctly
[tested on live usb]

https://user-images.githubusercontent.com/68134588/205680715-8a2b69de-b8ba-4a4a-b4d0-6590d5f5f01d.mp4

[logs .zip](https://github.com/linuxmint/mint21.1-beta/files/10155643/logs.zip)

**Comment by mtwebster** [comment]
Works here, can you run:
```
NEMO_DEBUG=Actions nemo --debug
```

It's pretty verbose, but it should show what exactly is being executed for that action.

**Comment by haggen88** [comment]
@mtwebster  [terminal output.zip](https://github.com/linuxmint/mint21.1-beta/files/10156428/terminal.output.zip)

**Comment by carlosmintfan** [comment]
But there's another issue here: When you right-click and choose to make a bootable usb stick, then you have to select the iso manually again!

**Comment by mtwebster** [comment]
Move the iso to a folder with no spaces and try it. I can reproduce this issue when there are spaces in the path.

**Comment by haggen88** [comment]
> Move the iso to a folder with no spaces and try it. **I can reproduce this issue when there are spaces in the path**.

I confirm that

**Comment by hitobashira** [comment]
nemo actions. I don't know if it will be helpful, but it will also fail in the following cases.

`Exec=bash -c '7zz a -mx0 -mmt12 "%F".cb7 "%F" && sleep 1'`

I use about 60 nemo actions, but most of them fail.
What they have in common is

 cd "%F"

Exec=alacritty -e bash -c 'cd "%F" && my image_file_cutter'

If there is
Most of my directories contain spaces.

**Comment by clefebvre** [comment]
Fixed in mintstick 1.5.4.

**Comment by clefebvre** [comment]
@hitobashira make sure you remove quotes around %F in your actions.

`Exec=bash -c '7zz a -mx0 -mmt12 "%F".cb7 "%F" && sleep 1'`

should be 

`Exec=bash -c '7zz a -mx0 -mmt12 %F.cb7 %F && sleep 1'`

**Comment by veractor** [comment]
For @hitobashira's case, even if the quotes around %F were removed, there will still be problems with some paths, which when actioned on, may not work at all. I've filed this in https://github.com/linuxmint/nemo/issues/3138.
