### ISSUE TITLE
Xreader crashes deleting annotations

### ISSUE THREAD

**Issue by jbergengh** [linuxmint/mint21.1-beta#80]
I just wanted to post a reminder that Xreader still crashes when deleting annotations.
I posted this bug report a while back as issue #564.  I just updated the issue with more info.
This is a repeatable, full-on crash of Xreader.  I've learned to work around it, but it still catches me off guard and I lose work occasionally.

https://github.com/linuxmint/xreader/issues/564

UPDATE:  Atril crashes exactly the same way in this Mint Mate beta.

**Comment by haggen88** [comment]
I confirm the bug
.
mint@mint:~$ xreader
Segmentation fault (core dumped)
.
[logs.zip](https://github.com/linuxmint/mint21.1-beta/files/10221714/logs.zip)

**Comment by mtwebster** [comment]
This should be fixed in 3.6.1 (in the beta). Please confirm when you get a chance.

Thanks!

**Comment by jbergengh** [comment]
@mtwebster 3.6.1 fixed the issue but seems to have created another.

Open a PDF
Add an annotation
Immediately right click the annotation and remove it.
Xreader 3.6.1 crashes.

BTW, in case you didn't notice, Atril has the same issue.

**Comment by mtwebster** [comment]
Ah sorry, fixed it - https://github.com/linuxmint/xreader/commit/b4b3a3ca2d95d0e9272517234085a4f0cf73baea

Someone needs to test more...

Not sure we'll get another version out today - if you want to re-check it, you can get the auto-build packages:
https://github.com/linuxmint/xreader/releases.

**Comment by jbergengh** [comment]
@mtwebster I'm more than happy to test it, but I'm not smart enough to know what to do with those auto-build packages.
I'll wait for version 3.6.2
Xreader has some other issues I need to submit as well.  It saves bookmarks without asking, and sometimes doesn't save annotations when you hit save.  No doubt you've got your hands full now, so I figure these can wait.

**Comment by mtwebster** [comment]
Yeah I noticed a bunch of things related to annotations alone (most annoying for me was the expanders in the annotation list always closing) - it definitely needs some attention.

**Comment by haggen88** [comment]
@mtwebster  so far 3.6.1 seems to fix the problem
