### ISSUE TITLE
window-list applet doesn't show the windows moved to Display 1

### ISSUE THREAD

**Issue by florisvdh** [linuxmint/mint21.1-beta#82]
This is a duplicate of https://github.com/linuxmint/cinnamon/issues/11319, but given that it only appeared since Mint 21, IMHO seems worth solving in 21.1, where it still occurs in the beta release.

[~/.xsession-errors](https://github.com/linuxmint/mint21.1-beta/files/10230045/xsession-errors2.txt)

To **reproduce**:

1. - Use Display 2 – typically an external monitor connected to a laptop – as **sole** display, i.e. Display 1 is inactive.
    - Also, use the window-list applet in a panel.
    - Open multiple windows (no matter what).
3. Now activate Display 1 (laptop screen) in the Display settings window (from Settings), use it as extended desktop, still with Display 2 as the primary display.
4. Move a window from Display 2 to Display 1, if not already the case after previous step.

**Observation**: the window-list only shows windows that are on Display 2, so the windows on Display 1 are inaccessible there (hence cannot be focused on if they are behind another window, except with Alt+Tab).

**Expected**: windows from both displays (in the same workspace) should be present in the window-list.

**Workaround**: restart cinnamon with Ctrl+Alt+Esc, but that is an inconvenience. Such restart is included in the above `~/.xsession-errors`.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/4b2713dac582b85dffa1160f09eee3d2a45e7484

**Comment by clefebvre** [comment]
Fixed

**Comment by florisvdh** [comment]
Thank you so much!
