### ISSUE TITLE
Nemo (icon view) - without moving the cursor at all, hovering over one item then scrolling and then right-clicking on a different item selects the first item rather than the second

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#83]
(not only occurs in Cinnamon but also occurs in Mate and Xfce if you manually install Nemo on those)

It is imperative that you *do not move the cursor at all* while scrolling nor before you right-click.

[scrolling then right-click.webm](https://user-images.githubusercontent.com/11896003/207731315-0a1551f8-7366-4dca-aa46-848ce5cc6fe2.webm)

**Comment by clefebvre** [comment]
I wonder if that's a GTK bug... either way, this is not a release blocker. Marking as to be fixed later.

**Comment by clefebvre** [comment]
Upstream: Gtk.
