### ISSUE TITLE
cinnamon: change the icon for "All Applications" in the main menu

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21.1-beta#84]
Currently the icon for all applications uses the start-here icon, depending on which icon you use eg Yaru uses the Ubuntu logo, Breeze uses it.  Plasma logo, it's better to use a generic icon like view-app-list-symbolic as shown in the image below
![203839075-60b3575e-fc36-47ff-8d2d-e0ed8548d27f](https://user-images.githubusercontent.com/59381215/207744633-1afd2fe1-5dce-4e77-9d59-2f8b9e517a6a.png)
![203838170-ba00a190-bf72-40b6-b170-702f9e6cf39d](https://user-images.githubusercontent.com/59381215/207744639-9b7f2158-96ef-48f1-82ec-f1d651310095.png)

**Comment by Initu-Castilhos** [comment]
In my opinion it makes more sense to use the view-list icon because it is a menu.

**Comment by clefebvre** [comment]
Confirmed

**Comment by clefebvre** [comment]
Fixed on master.
