### ISSUE TITLE
cinnamon: PC wakes up from "turned-off screen" into screensaver

### ISSUE THREAD

**Issue by Thunderschnozzle** [linuxmint/mint21.1-beta#85]
Linux distro: Linux Mint 21.1
Cinnamon version: 5.6.4

How to reproduce the problem:
In System Settings >> Screensaver, set the "Delay before starting the screensaver" option to X minutes (I set mine to 5 minutes) and toggle off the "Lock the computer after the screensaver starts" option.
Then, in System Settings >> Power Management, set the "Turn off the screen when inactive" option to some value bigger than X (I've set mine to 10 minutes).
Finally, leave the PC idle until the screen turns off and then move the mouse or press any bottom on your keyboard.

what I expect to happen:
The PC should wake straight into the desktop

What actually happens:
The PC wakes up into the screensaver, requiring another mouse motion / key pressing to "wake it up" into the desktop.

This bug happens consistently.

**Comment by clefebvre** [comment]
If I understand right, it should start the screensaver after 5 minutes, and then turn off the screen after another 5.

When you wake the screen you're still in the screensaver, that doesn't seem abnormal to me.

If you only want the screen to go off and not have to deal with the screensaver, then set it to a higher value. Say 10 minutes for the screen, 30 minutes with locking for the screensaver?

**Comment by Thunderschnozzle** [comment]
I'm not sure I understood that last paragraph, but your understanding of my
issue is correct. What I was trying to do is create a nice/gradual
transition towards suspend mode that went like this: screensaver --> screen
turns off ---> suspend. It doesn't have any practical usage, I just like
the gradual transition, that's all.

I was under the impression that when the screen turns off it causes the
screensaver to quit (because what's the point of the screensaver continuing
to work in the background when the screen is turned off). Therefore, when I
woke up the screen I expected to get back immediately to the desktop. But I
guess my understanding of the situation was incorrect.

Anyways, for now I just set the screensaver delay to "Never", screen turn
off delay to "5 minutes" and suspend delay to "15 minutes". This completely
eliminates the problem.

You can close this issue if you want.

Thanks for looking into this for me, and keep up the good work.

**Comment by clefebvre** [comment]
Thanks @Thunderschnozzle. 

The screensaver really is a screen locker nowadays. Historically its most important function was to reduce wear and prevent burn-in (the same picture shown on the same pixels without movement for a long period of time would eventually mark the screen and stay there forever). I'm not an expert when it comes to LED/Plasma etc.. but my understanding is that this is no longer as much of an issue. What the screensaver really does here is lock your screen. It's designed to be ready to do that and to make sure to remain locked no matter what.

If as a locker, it exited on suspend, or screen power events, in the hope of coming back on time for when the screen wakes up or the computer resumes, there'd be a security risk. There could be a moment during which the locker isn't live.. or it could fail to start altogether.
