### ISSUE TITLE
[Mate & Xfce] Despite having no wifi devices, disabling then re-enabling networking via right click (not left) shows that wifi is disconnected

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#87]
(since I do not know how to disable all network devices at one time on Cinnamon, I was only able to replicate this on Mate and Xfce)

This only occurs when disabling all network devices via right-clicking; selecting `disconnect` from the left-click menu does not cause this issue.

[video.webm](https://user-images.githubusercontent.com/11896003/207954591-abe297b3-8544-4bb1-bbeb-4d22155ef8a5.webm)

**Comment by clefebvre** [comment]
This is upstream (network-manager-applet/network-manager-gnome).
