### ISSUE TITLE
Nemo - files opened via a search result are treated as if the files are actually located in that search result rather than their source folders

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#89]
(not only occurs in Cinnamon but also occurs in Mate and Xfce if you manually install Nemo on those)

This occurs in both v5.6.0 and v5.6.1

And, to be clear, this isn't an Xviewer issue and it also impacts other applications, it's just that demonstrating it with Xviewer was an easy way to show the issue (this issue is actually particularly problematic with WINE applications, e.g. dragging audio files from a Nemo search result into a foobar2000 playlist)

For context, Caja and Catfish do not have this issue.

[nemo.webm](https://user-images.githubusercontent.com/11896003/207970021-48a452a0-29c6-4b6d-acc1-d79cbd279d2c.webm)

**Comment by MenthaSuaveolens** [comment]
This looks as a great feature for me! In this way, I can view all the images that match the search-criteria.

**Comment by mtwebster** [comment]
I don't know what you're showing me - this looks fine, and the behavior I'd expect.

If I search for images, I want to operate on the results of that search, not make opening a single item transport me into its folder if I interact with it. The search results list is treated as an actual folder for a reason.

I expect:
- If I open a file with an editor, try to save it, it saves to its 'real' location.
- If I drag a file to another location, it succeeds.
- If I try to link a file, it links to its original location.
All of this works properly.

I'm not going to try to accommodate wine - wine needs to make their drag-and-drop implementation work correctly.
