### ISSUE TITLE
mintbackup 

### ISSUE THREAD

**Issue by deck-luck** [linuxmint/mint21.1-beta#91]
Problem:

The mintbackup program  does not produce or save a list of Software Manager
installed packages.

 
Steps to reproduce the anomaly:

Start mintbackup
In the Software selection section select the "BackUp Now" button.
The next window indicates the following:
   The list below shows the applications you installed with Software Manager 

The list is empty; even though, I have previously used the Software Manager to
install the ncdu package.  After hitting Forward button it pretends to
successfully complete.  See the mintbackup terminal session output for
additional error messages.

Terminal session output:

$ date
Thu Dec 15 06:51:31 PM CST 2022

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

$ apt list ncdu
Listing... Done
ncdu/jammy,now 1.15.1-1 amd64 [installed]

$ mintbackup
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 52, in wrapper
    res = func(*arg)
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 694, in backup_pkg_load_from_mintinstall
    pkgcache = PkgCache()
TypeError: PkgCache.__init__() missing 1 required positional argument: 'pkg_type'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintbackup_mintbackup.py.1001.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 52, in wrapper
    res = func(*arg)
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 694, in backup_pkg_load_from_mintinstall
    pkgcache = PkgCache()
TypeError: PkgCache.__init__() missing 1 required positional argument: 'pkg_type'

Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 368, in forward_callback
    self.backup_pkg_save_to_file()
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 740, in backup_pkg_save_to_file
    for row in self.builder.get_object("treeview_packages").get_model():
TypeError: 'NoneType' object is not iterable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintbackup_mintbackup.py.1001.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 368, in forward_callback
    self.backup_pkg_save_to_file()
  File "/usr/lib/linuxmint/mintbackup/mintbackup.py", line 740, in backup_pkg_save_to_file
    for row in self.builder.get_object("treeview_packages").get_model():
TypeError: 'NoneType' object is not iterable

$ 

$ apt list mintbackup
Listing... Done
mintbackup/vera,vera,now 2.4.2 all [installed]

$

$ cd /home/webuser/Documents/Backups

$ ls -l *packages.list
-rw-rw-r-- 1 webuser webuser 0 Dec 15 18:55 2022-12-15-1855-packages.list

$ 

'

**Comment by clefebvre** [comment]
Looks like a regression from mint-common/mintinstall changes.

**Comment by carlosmintfan** [comment]
Because you ported AptDaemon to PackageKit?

**Comment by carlosmintfan** [comment]
Ah, did you port mintbackup to Packagekit too?
Do you prefer it?

**Comment by carlosmintfan** [comment]
@mtwebster Do you prefer packagekit over aptdaemon?

**Comment by mtwebster** [comment]
Mintbackup has been using our installer in mint-common - we ported *that* to use packagekit instead.

I prefer packagekit for a few reasons:

- aptdaemon seemed a bit brain-dead at times trying to resolve dependencies - not sure why they'd be different while using apt underneath, but apt has multiple ways to do a lot of things so I imagine there is some potential for different behavior.
- packagekit uses GLib/GObject which we're familiar with, and its API is fairly similar to Flatpak's, which is great when dealing with both types of packages in the software and update managers.  Aptdaemon's was weird and clunky to me.
