### ISSUE TITLE
xfce: thunar segmentation fault

### ISSUE THREAD

**Issue by bluecoat58** [linuxmint/mint21.1-beta#93]
After the last update (Dec15) Thunar can no longer access local network folders on linux machines. Click on "Browse Network" then click the network folder..at that point it does a Segmentation fault (core dumped). For all other file operations I haven't noticed any issues.
[jim.zip](https://github.com/linuxmint/mint21.1-beta/files/10242374/jim.zip)

When I tested the live media, thunar browsed the network just fine. But, after installation it did the segmentation fault.  After I updated and rebooted it was fine again. Now with the latest update I'm back to the same issue.

**Comment by clefebvre** [comment]
Thunar had no update recently.

We'll need more info to chase this.

- stack trace for the crash (in mintreport)
- make sure the problem NEVER happens prior to updates
- make sure the problem ALWAYS happens after updates
- if so, identify which update triggers the issue

It's probably upstream also, thunar, gvfs, samba? it's hard to know for now, but we don't develop any of these directly ourselves.
