### ISSUE TITLE
Software Manager - 'Packages have unmet dependancies' error and solid-white 'Remove' button when trying to install Nemo if you change software sources but don't update APT cache and don't regenerate Software Manager's cache

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#96]
(occurs not only in Mate and Xfce but even in Cinnamon if you manually uninstall Nemo first)

[video.webm](https://user-images.githubusercontent.com/11896003/208233620-7556655f-780a-45a4-a181-9ffb678cfce6.webm)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/mintcommon/commit/1ee060fec9cd4896efc1b1fd2319342993330612
